title: TITAN Project
description: Vulnerability detection with LLMs
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

# Optional: Customize navigation (used by some themes)
navigation:
  - title: Home
    url: /
  - title: Papers
    url: /papers/
